### ISSUE TITLE
Panic in compression when a name lacks a trailing dot

### ISSUE THREAD

**Issue by wttw** [benburkert/dns#2]
If the fqdn passed to MessageWriter.Reply lacks a trailing dot then compressor.Pack will panic at [line 79](https://github.com/benburkert/dns/blob/737ce0376169e5410fb2a4ae066d5aabbb71648c/compression.go#L89) due to slice bound being out of range.

A simple way to replicate it is to change TestQuestionPackUnpack to include a question like this:

```
			question: Question{
				Name:  "google.com",
				Type:  TypeAAAA,
				Class: ClassIN,
			},
```

I'm not sure whether the right fix is to return an error due to the malformed name, or to silently append a dot, but it seems like something a typical user is going to run across a lot.

**Comment by benburkert** [comment]
Thanks for reporting this bug, it should be fixed now that the `Pack` & `Length` methods returns an `"invalid FQDN"` error for domains that do not end with a `.` suffix.
