### ISSUE TITLE
How are timeouts handled?

### ISSUE THREAD

**Issue by xeoncross** [benburkert/dns#4]
I would like to use this [library for a local DNS client cache](https://github.com/benburkert/dns/blob/master/init/init.go), but I don't see anything for setting timeouts for the handler. It's possible to use context.Context to define a timeout with a custom net.Resolver.

```
    const timeout = 10 * time.Millisecond
    ctx, cancel := context.WithTimeout(context.TODO(), timeout)
    defer cancel() // important to avoid a resource leak
    var r net.Resolver
    names, err := r.LookupMX(ctx, "127.0.0.1")
```

https://play.golang.org/p/HTW6-2o0qeT

**Comment by benburkert** [comment]
The deadline context passed into `LookupMX` is used for the read/write deadline for the `net.Conn` used in the DNS query, but the context is not passed through to the `dns.Client.Resolver` handler. However, the deadline should be applied to the connection used by the `dns.Client` in the event that the handler calls `Recur`, which happens on a cache miss in the `dns.Cache` handler.

**Comment by xeoncross** [comment]
Sorry, I'm not clear on your comment. Are you saying I can provide a deadline context to `benburkert/dns` which will work because `Recur` will respect it? I don't see [anything in the code](https://github.com/benburkert/dns/blob/97af4bf9414d912fd499d215547ae3df9bfbe581/client.go#L154) for this.

**Comment by benburkert** [comment]
The `net.Resolver` converts the context's timeout into a [deadline on the underlying connection](https://github.com/golang/go/blob/a10b4cff91cb5d26e2049f6efc20349aa4d50d20/src/net/dnsclient_unix.go#L149). That deadline is applied to reads/writes over the underlying connection when `Recur` sends/recv's messages to an upstream server.

**Comment by xeoncross** [comment]
So how should I go about combining the [DNS cache](https://github.com/benburkert/dns/blob/master/init/init.go#L19) + Go's default support for dialer deadlines to correctly use this package as a DNS cache?

```
package main

import (
	"context"
	"fmt"
	"log"
	"net"
	"time"

	"github.com/benburkert/dns"
)

func NewResolver() *net.Resolver {
	return &net.Resolver{
		PreferGo: true,

		Dial: (&dns.Client{
			Resolver: new(dns.Cache),
		}).Dial,
	}
}

func main() {

	resolver := NewResolver()

	const timeout = 10 * time.Millisecond
	ctx, cancel := context.WithTimeout(context.TODO(), timeout)
	defer cancel() // important to avoid a resource leak

	r, err := resolver.LookupMX(ctx, "example.com")
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(r)
}

```

**Comment by benburkert** [comment]
Yes, that looks right to me.
